screen=[FLASHLIGHT_CONFIG] FLASHLIGHT_FLICKER VOLUMETRIC_INTENSITY AMBIENT_BRIGHTNESS 
screen.FLASHLIGHT_CONFIG=FLASHLIGHT_RANGE CORE_BRIGHTNESS HALO_BRIGHTNESS SPILL_BRIGHTNESS CORE_SIZE HALO_SIZE 
sliders=FLASHLIGHT_RANGE AMBIENT_BRIGHTNESS CORE_BRIGHTNESS HALO_BRIGHTNESS SPILL_BRIGHTNESS CORE_SIZE HALO_SIZE VOLUMETRIC_INTENSITY

const.FLASHLIGHT_FLICKER.0=false
const.FLASHLIGHT_FLICKER.1=true
