screen=[FLASHLIGHT_CONFIG] FLASHLIGHT_FLICKER VOLUMETRIC_INTENSITY AMBIENT_BRIGHTNESS 
screen.FLASHLIGHT_CONFIG=FLASHLIGHT_RANGE [CORE_SETTINGS] [HALO_SETTINGS] [SPILL_SETTINGS]
screen.CORE_SETTINGS=CORE_BRIGHTNESS CORE_SIZE CORE_RED CORE_GREEN CORE_BLUE CORE_SATURATION
screen.HALO_SETTINGS=HALO_BRIGHTNESS HALO_SIZE HALO_RED HALO_GREEN HALO_BLUE HALO_SATURATION
screen.SPILL_SETTINGS=SPILL_BRIGHTNESS SPILL_RED SPILL_GREEN SPILL_BLUE SPILL_SATURATION

sliders=FLASHLIGHT_RANGE AMBIENT_BRIGHTNESS CORE_BRIGHTNESS HALO_BRIGHTNESS SPILL_BRIGHTNESS CORE_SIZE HALO_SIZE VOLUMETRIC_INTENSITY CORE_RED CORE_GREEN CORE_BLUE HALO_RED HALO_GREEN HALO_BLUE SPILL_RED SPILL_GREEN SPILL_BLUE SPILL_SATURATION HALO_SATURATION CORE_SATURATION

const.FLASHLIGHT_FLICKER.0=false
const.FLASHLIGHT_FLICKER.1=true
